import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Libre_Baskerville } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar/sidebar";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const libre = Libre_Baskerville({
  variable: "--font-libre",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Smart Chapters",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${libre.variable} antialiased text-primaryText`}
      >
        {/* sidebar */}
        <div className="flex justify-between w-full h-screen gap-2 p-2 bg-background">
          <Sidebar />
          {/* main content */}
          <div className="flex-1 overflow-auto bg-foreground font-libre p-2 rounded-xl">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
