import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Libre_Baskerville } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { SessionProvider } from "next-auth/react";
import React from "react";
import { Toaster } from "sonner";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const libre = Libre_Baskerville({
  variable: "--font-libre",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Smart Chapters",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="" suppressHydrationWarning>
      <body
        className={`${inter.variable} ${libre.variable}  antialiased text-primaryText`}
      >
        <SessionProvider>
          <SidebarProvider>{children}
            <Toaster/>
          </SidebarProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
