import type { Metadata } from "next";
import { Libre_Baskerville, Inter, Merriweather } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/components/Sidebar/sidebar";
import { SessionProvider } from "next-auth/react";
import React from "react";
import { Toaster } from "sonner";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const libre = Libre_Baskerville({
  variable: "--font-libre",
  subsets: ["latin"],
  weight: "400",
});

const merriweather = Merriweather({
  variable: "--font-merriweather",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Smart Chapters",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <body
        className={`${inter.variable}  ${libre.variable} ${merriweather.variable} antialiased text-primaryText`}
      >
        <SessionProvider>
          <SidebarProvider>
            {children}
            <Toaster />
          </SidebarProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
