import { TrackingStatus } from "@prisma/client";
import { hashSync } from "bcrypt-ts";

export const simpleData = {
  users: [
    {
      id: "user1",
      name: "Alice Johnson",
      email: "alice@example.com",
      passwordHash: hashSync("123456", 10),
      role: "user",
      image: "/avatar01.jpg",
      paymentMethod: "card",
    },
    {
      id: "user2",
      name: "Bob Smith",
      email: "bob@example.com",
      passwordHash: hashSync("123456", 10),
      role: "user",
      image: "/avatar02.jpg",
      paymentMethod: "paypal",
    },
    {
      id: "user3",
      name: "Charlie Evans",
      email: "charlie@example.com",
      passwordHash: hashSync("123456", 10),
      role: "user",
      image: "/avatar01.jpg",
      paymentMethod: "stripe",
    },
    {
      id: "user4",
      name: "Diana Lee",
      email: "diana@example.com",
      passwordHash: hashSync("123456", 10),
      role: "user",
      image: "/avatar02.jpg",
      paymentMethod: "paypal",
    },
    {
      id: "user5",
      name: "Ethan Brown",
      email: "ethan@example.com",
      passwordHash: hashSync("123456", 10),
      role: "user",
      image: "/avatar02.jpg",
      paymentMethod: "credit_card",
    },
    {
      id: "user6",
      name: "Fiona Carter",
      email: "fiona@example.com",
      passwordHash: hashSync("123456", 10),
      role: "user",
      image: "/avatar01.jpg",
      paymentMethod: "paypal",
    },
    {
      id: "user7",
      name: "George Harris",
      email: "george@example.com",
      passwordHash: hashSync("123456", 10),
      role: "user",
      image: "/avatar01.jpg",
      paymentMethod: "stripe",
    },
    {
      id: "user8",
      name: "Hannah White",
      email: "hannah@example.com",
      passwordHash: hashSync("123456", 10),
      role: "user",
      image: "/avatar02.jpg",
      paymentMethod: "credit_card",
    },
    {
      id: "user9",
      name: "Ian Walker",
      email: "ian@example.com",
      passwordHash: hashSync("123456", 10),
      role: "user",
      image: "/avatar01.jpg",
      paymentMethod: "paypal",
    },
    {
      id: "user10",
      name: "Julia Adams",
      email: "julia@example.com",
      passwordHash: hashSync("123456", 10),
      role: "user",
      image: "/avatar1.jpg",
      paymentMethod: "stripe",
    },
  ],

  bookTrackings: [
    {
      userId: "user1",
      bookId: "the-midnight-library-clm1a2b3c4d5e6f7g8h9i0j1",
      status: TrackingStatus.READING,
      currentPage: 45,
      rating: 4,
      notes: "Enjoying the vivid descriptions.",
      startedAt: new Date("2025-07-01"),
      finishedAt: null,
    },
    {
      userId: "user2",
      bookId: "dune-clm4d5e6f7g8h9i0j1k2l3m4",
      status: TrackingStatus.WANT_TO_READ,
      currentPage: 36,
      rating: 4,
      notes: null,
      startedAt: null,
      finishedAt: null,
    },
    {
      userId: "user1",
      bookId: "dune-clm4d5e6f7g8h9i0j1k2l3m4",
      status: TrackingStatus.READING,
      currentPage: 161,
      rating: 3,
      notes: null,
      startedAt: null,
      finishedAt: null,
    },
    {
      userId: "user1",
      bookId: "atomic-habits-clm2b3c4d5e6f7g8h9i0j1k2",
      status: TrackingStatus.FINISHED,
      currentPage: 114,
      rating: 5,
      notes: null,
      startedAt: null,
      finishedAt: null,
    },
  ],
  reviews: [
    {
      userId: "user1",
      bookId: "the-midnight-library-clm1a2b3c4d5e6f7g8h9i0j1",
      rating: 5,
      content:
        "There are books you read, and there are books that read you back. The Midnight Library is one of those rare treasures.",
    },
    {
      userId: "user2",
      bookId: "the-midnight-library-clm1a2b3c4d5e6f7g8h9i0j1",
      rating: 3,
      content:
        "Captivating premise with poetic prose, but dragged in the middle.",
    },
    {
      userId: "user2",
      bookId: "dune-clm4d5e6f7g8h9i0j1k2l3m4",
      rating: 4,
      content: "Epic in scope and themes — a sci-fi classic worth the read.",
    },
    {
      userId: "user1",
      bookId: "atomic-habits-clm2b3c4d5e6f7g8h9i0j1k2",
      rating: 5,
      content: "Life-changing in small, consistent steps. Brilliant book.",
    },
    {
      userId: "user1",
      bookId: "the-psychology-of-money-clm5e6f7g8h9i0j1k2l3m4n5",
      rating: 5,
      content: "Deep insights on human behavior and money habits.",
    },
    {
      userId: "user2",
      bookId: "project-hail-mary-clm6f7g8h9i0j1k2l3m4n5o6",
      rating: 5,
      content: "Funny, thrilling, and unexpectedly emotional sci-fi adventure.",
    },
    {
      userId: "user1",
      bookId: "where-the-crawdads-sing-clm9i0j1k2l3m4n5o6p7q8r9",
      rating: 4,
      content: "Nature and mystery beautifully intertwined.",
    },
    {
      userId: "user2",
      bookId: "sapiens-clm0j1k2l3m4n5o6p7q8r9s0",
      rating: 5,
      content: "A fascinating, sweeping look at human history.",
    },
    {
      userId: "user1",
      bookId: "the-poppy-war-clm9s0t1u2v3w4x5y6z7a8b9",
      rating: 5,
      content: "Dark, intense, and utterly gripping.",
    },
    {
      userId: "user2",
      bookId: "the-martian-clm0t1u2v3w4x5y6z7a8b9c0",
      rating: 4,
      content: "Hilarious and tense — a love letter to science and survival.",
    },
    {
      userId: "user3",
      bookId: "dune-clm4d5e6f7g8h9i0j1k2l3m4",
      rating: 5,
      content: "Political intrigue meets space opera. Outstanding.",
    },
    {
      userId: "user4",
      bookId: "atomic-habits-clm2b3c4d5e6f7g8h9i0j1k2",
      rating: 4,
      content: "Solid advice for building habits that last.",
    },
    {
      userId: "user5",
      bookId: "sapiens-clm0j1k2l3m4n5o6p7q8r9s0",
      rating: 4,
      content: "Makes you think differently about our species.",
    },
    {
      userId: "user6",
      bookId: "the-martian-clm0t1u2v3w4x5y6z7a8b9c0",
      rating: 5,
      content: "Tense and clever, full of problem-solving joy.",
    },
    {
      userId: "user7",
      bookId: "project-hail-mary-clm6f7g8h9i0j1k2l3m4n5o6",
      rating: 5,
      content: "A survival story like no other — and hilarious too.",
    },
    {
      userId: "user8",
      bookId: "the-poppy-war-clm9s0t1u2v3w4x5y6z7a8b9",
      rating: 4,
      content: "Grim and powerful. Not for the faint-hearted.",
    },
    {
      userId: "user9",
      bookId: "where-the-crawdads-sing-clm9i0j1k2l3m4n5o6p7q8r9",
      rating: 5,
      content: "Evocative writing and a touching story.",
    },
    {
      userId: "user10",
      bookId: "the-psychology-of-money-clm5e6f7g8h9i0j1k2l3m4n5",
      rating: 5,
      content: "Financial wisdom in simple, relatable language.",
    },
    {
      userId: "user6",
      bookId: "the-midnight-library-clm1a2b3c4d5e6f7g8h9i0j1",
      rating: 4,
      content: "A moving exploration of regret and possibility.",
    },
    {
      userId: "user8",
      bookId: "the-martian-clm0t1u2v3w4x5y6z7a8b9c0",
      rating: 5,
      content: "I couldn’t put it down — pure adrenaline.",
    },
    {
      userId: "user9",
      bookId: "the-martian-clm0t1u2v3w4x5y6z7a8b9c0",
      rating: 4,
      content: "Felt like I was stranded on Mars myself. Absolutely thrilling!",
    },
    {
      userId: "user10",
      bookId: "the-martian-clm0t1u2v3w4x5y6z7a8b9c0",
      rating: 4,
      content: "Great concept, but some chapters dragged on a bit.",
    },
    {
      userId: "user4",
      bookId: "the-martian-clm0t1u2v3w4x5y6z7a8b9c0",
      rating: 3,
      content: "Witty, smart, and full of heart. Andy Weir nailed it.",
    },
    {
      userId: "user9",
      bookId: "the-poppy-war-clm9s0t1u2v3w4x5y6z7a8b9",
      rating: 5,
      content: "Heart-wrenching and unforgettable.",
    },
    {
      userId: "user10",
      bookId: "where-the-crawdads-sing-clm9i0j1k2l3m4n5o6p7q8r9",
      rating: 4,
      content: "Atmospheric and beautifully written.",
    },
  ],
};
